module.exports = {
  content: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {
      bg: "#1F3757",
      score: "#2A45C2",
      scoreNum: "#565468",
      selector: "#000000",
      icon: "#3B4262",
      rulesIcon: "#8A90AC",
      rulesIconBg: "#E1E4ED",
      rules: "#B1B4C5",
      iconSh: "#BABFD4",
      scissors: "#EB9F0E",
      scissorsSh: "#C76C1B",
      paper: "#4664F4",
      paperSh: "#2A45C2",
      rock: "#DB2E4D",
      rockSh: "#9D1634",
      lizard: "#834EE3",
      lizardSh: "#5F37A8",
      spock: "#3FB7CD",
      spockSh: "#2D8DAB",
      playHover: "#DB2E4D",
      white: "#FFFFFF",
    },
    fontFamily: {
      main: "Barlow Semi Condensed",
    },
    extend: {},
  },
  plugins: [],
};
